export const MOVIE_LIST_REQUEST = 'MOVIE_LIST_REQUEST'
export const MOVIE_LIST_SUCCESS = 'MOVIE_LIST_SUCCESS'
export const MOVIE_LIST_FAIL = 'MOVIE_LIST_FAIL'
export const MOVIE_LIST_RESET = 'MOVIE_LIST_RESET'

export const MOVIE_DETAILS_REQUEST = 'MOVIE_DETAILS_REQUEST'
export const MOVIE_DETAILS_SUCCESS = 'MOVIE_DETAILS_SUCCESS'
export const MOVIE_DETAILS_FAIL = 'MOVIE_DETAILS_FAIL'
export const MOVIE_DETAILS_RESET = 'MOVIE_DETAILS_RESET'

export const MOVIE_REVIEWS_REQUEST = 'MOVIE_REVIEWS_REQUEST'
export const MOVIE_REVIEWS_SUCCESS = 'MOVIE_REVIEWS_SUCCESS'
export const MOVIE_REVIEWS_FAIL = 'MOVIE_REVIEWS_FAIL'
export const MOVIE_REVIEWS_RESET = 'MOVIE_REVIEWS_RESET'


